profile_analysis:
  description: >
    分析使用者原始請求: {user_query}。
    提取並結構化關鍵資訊：個案年齡、所在縣市/行政區、描述的身體限制（與ADL相關）、認知問題（記憶喪失、混亂）以及目前的居住情況。
    將這些資訊格式化為一份清晰、結構化的個案摘要。
  expected_output: >
    一個結構化的Markdown物件，包含'個案年齡', '所在地區', '身體功能問題', '認知功能問題', '社會家庭背景'等獨立欄位。

needs_assessment:
  description: >
    審閱結構化的個案摘要。基於台灣長照2.0法規與CMS框架，進行臨床評估。
    判斷個案是否符合長照2.0服務資格。若符合資格，推斷其CMS失能等級（從2到8級）。
    請引用ADL/IADL標準，為你的評估提供具體理由。
  expected_output: >
    一份正式的評估報告，內容包括：
    1. 資格狀態 (符合/不符合)。
    2. 推斷的CMS等級 (例如：'CMS第5級 - 中度失能')。
    3. 評估的理由，將個案問題與特定的ADL/IADL缺失連結起來。

care_recommendation:
  description: >
    根據正式的需求評估報告，推薦最適合的長期照護『服務類別』。
    請從台灣官方的分類中選擇：'居家式', '社區式'或'機構住宿式'。
    在該類別中，請進一步指明子類型（例如：'日間照顧中心', '護理之家'）。
    你的推薦必須基於CMS等級以及個案需求的性質（例如：醫療需求 vs. 社會支持需求）。
  expected_output: >
    一個單一、精確的照護類別與子類型推薦（例如：'社區式: 失智社區服務據點'），並附上簡短的選擇理由。

provider_search:
  description: >
    接收推薦的照護子類型以及來自個案摘要的使用者地點。
    使用你的專業搜尋工具，尋找5個符合這些條件的具體、具名的機構。
    為每個機構提供其名稱、地址和電話號碼。
  expected_output: >
    一份包含5個在地照護提供者的清單，清晰地格式化，列出每個機構的 (a) 名稱, (b) 地址, (c) 電話。

comprehensive_report:
  description: >
    整合所有先前任務的結果（個案摘要、臨床評估、照護建議、機構搜尋結果），撰寫一份專業的「長照2.0出院準備暨轉銜服務顧問報告」。
    報告必須使用 Markdown (.md) 格式，並嚴格遵循以下結構與標題：

    ---
    # 長照2.0出院準備暨轉銜服務顧問報告

    ## 1. 個案摘要
    (在此處重述來自`profile_analysis`任務的結構化個案摘要)

    ## 2. 類出院準備評估
    ### 高危因子分析
    (根據個案摘要，條列出個案符合出院準備服務介入的高風險因子，例如：高齡、獨居、多重身體或認知功能障礙等。)
    ### 長照2.0需求評估
    (整合`needs_assessment`任務的結果，說明個案符合長照2.0資格，並明確指出推斷的CMS失能等級及其判斷依據。)

    ## 3. 無縫長照銜接計畫
    ### 服務模式建議
    (整合`care_recommendation`任務的結果，說明為何推薦該服務模式，例如：社區式-日間照顧中心，並解釋其如何滿足個案需求。)
    ### 推薦轉介機構
    (整合`provider_search`任務的結果，條列出5個具體機構的名稱、地址和電話。)
    ### 出院前準備建議
    (根據"出院前3天接軌服務"的概念，提供家屬具體的下一步行動建議，例如：建議家屬可於服務啟用前一週，開始聯繫推薦機構，預約參觀並了解細節。)

    ## 4. 後續追蹤與資源
    ### 服務啟用與追蹤
    (根據"出院後7天接受服務"的概念，提醒家屬服務啟用的重要性，並建議應與個案管理師保持溝通，定期追蹤個案狀況。)
    ### 重要資源
    (再次提醒撥打 1966 長照專線的重要性，說明他們可以提供官方的評估與資源連結。)
    ---
  expected_output: >
    一份格式完整的 Markdown (.md) 文件。這份文件應直接呈現給使用者，包含所有上述指定的章節和內容，標題和結構需完全一致，內容專業、清晰、易於閱讀。
