profile_analysis:
  description: >
    分析使用者原始請求: {user_query}。
    提取並結構化關鍵資訊：個案年齡、所在縣市/行政區、描述的身體限制（與ADL相關）、認知問題（記憶喪失、混亂）、目前的居住情況、以及任何提及的財務或安全議題。
    將這些資訊格式化為一份清晰、結構化的個案摘要。
  expected_output: >
    一個結構化的Markdown物件，包含'個案年齡', '所在地區', '身體功能問題', '認知功能問題', '社會家庭背景', '潛在財務考量', '主要安全擔憂' 等獨立欄位。

needs_assessment:
  description: >
    審閱結構化的個案摘要。基於台灣長照2.0法規與CMS框架，進行臨床評估。
    判斷個案是否符合長照2.0服務資格。若符合資格，推斷其CMS失能等級（從2到8級）。
    請引用ADL/IADL標準，為你的評估提供具體理由。
    並根據推斷的CMS等級，簡述其對應的「照顧及專業服務」補助額度區間，以增加報告的實用性。
  expected_output: >
    一份正式的評估報告，內容包括：
    1. 資格狀態 (符合/不符合)。
    2. 推斷的CMS等級 (例如：'CMS第5級 - 中度失能')。
    3. 評估的理由，將個案問題與特定的ADL/IADL缺失連結起來。
    4. 對應的給付額度簡介（例如：CMS第5級對應每月約NT$24,100的照顧及專業服務額度）。

care_recommendation:
  description: >
    根據正式的需求評估報告，推薦一個整合性的長期照護策略。
    1. 推薦核心服務模式：從'居家式', '社區式'或'機構住宿式'中選擇，並指明子類型（例如：'日間照顧中心'）。
    2. 建議輔助服務：根據個案的IADL問題（如備餐、用藥），建議如「餐飲服務」、「居家專業服務（復健/護理）」等。
    3. 提出安全強化方案：針對獨居與跌倒風險，必須提出「緊急救援系統」與「輔具及居家無障礙環境改善」的建議。
  expected_output: >
    一份結構化的多層次照護建議，而非單一推薦。例如：{ "核心服務": "社區式: 日間照顧中心", "輔助服務": ["餐飲服務", "居家物理治療"], "安全措施": ["緊急救援系統安裝", "浴室防滑與扶手加裝評估"] }，並為每項建議附上簡短理由。

provider_search:
  description: >
    接收多層次照護建議以及來自個案摘要的使用者地點。
    針對每一項服務建議（例如：日間照顧中心、餐飲服務、緊急救援系統安裝單位），使用你的專業搜尋工具，尋找最多5個具體、具名的機構。
    為每個機構提供其名稱、地址和電話號碼。搜尋時必須驗證資訊的有效性，避免提供重複或過時的資料。
  expected_output: >
    一份分類清晰的在地資源清單。清單應按服務類型（如「日間照顧中心推薦」、「餐飲服務單位」）組織，每個類別下列出最多5個機構的 (a) 名稱, (b) 地址, (c) 電話。若有自費選項，應清楚標示。若某類別資源不足5個，應如實呈現並註明。

comprehensive_report:
  description: >
    整合所有先前任務的結果，撰寫一份專業的「長照2.0出院準備暨轉銜服務顧問報告」。
    報告必須使用 Markdown (.md) 格式，並嚴格遵循以下優化後的結構與標題：

    ---
    # 長照2.0出院準備暨轉銜服務顧問報告

    ## 1. 個案摘要
    (在此處重述來自`profile_analysis`任務的結構化個案摘要)

    ## 2. 類出院準備評估
    ### 高危因子分析
    (根據個案摘要，條列出個案符合出院準備服務介入的高風險因子)
    ### 長照2.0需求評估
    (整合`needs_assessment`任務的結果，說明個案符合長照2.0資格，明確指出推斷的CMS失能等級及其判斷依據，並附上對應的給付額度簡介)

    ## 3. 整合式照護策略建議
    ### 核心服務模式建議
    (整合`care_recommendation`任務的核心服務結果，說明為何推薦該服務模式)
    ### 輔助服務與安全強化方案
    (整合`care_recommendation`任務的輔助服務與安全措施建議，如餐飲、復健、緊急救援系統等)
    ### 在地資源轉介清單
    (整合`provider_search`任務的結果，分類條列出各項服務的具體機構名稱、地址和電話)

    ## 4. 給家屬的行動計畫與資源
    ### 您的下一步行動清單
    (提供家屬具體的下一步行動建議，例如：1. 優先聯繫1966啟動官方評估。2. 聯繫推薦機構預約參觀。3. 與父親溝通照護計畫。)
    ### 其他地方福利與自費選項參考
    (簡要提及個案所在地區可能適用的額外福利，或自費服務的市場行情，作為補充資訊。)
    ### 重要資源提醒
    (再次提醒撥打 1966 長照專線的重要性)
    ---
  expected_output: >
    一份格式完整的 Markdown (.md) 文件。這份文件應直接呈現給使用者，包含所有上述指定的章節和內容，標題和結構需完全一致，內容專業、清晰、易於閱讀。
